INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P001', N'Iphone 14', N'23', N'45000', N'3C')
INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P002', N'SamSung A52', N'10', N'23000', N'3C')
INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P003', N'SamSung S20', N'15', N'35200', N'3C')
INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P004', N'青森頻果原汁', N'100', N'370', N'飲料')
INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P005', N'綠茶(瓶裝)', N'1000', N'25', N'飲料')
INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P006', N'辛拉麵(袋裝)', N'1000', N'50', N'食品')
INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P007', N'台酒麻油雞泡麵(碗裝)', N'5000', N'53', N'食品')
INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P008', N'台酒花雕雞泡麵(碗裝)', N'10000', N'53', N'食品')
INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P009', N'台酒酸菜牛肉泡麵(碗裝)', N'12000', N'53', N'食品')
INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P010', N'滿漢大餐珍味牛肉麵(碗裝)', N'25080', N'53', N'食品')
INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P011', N'烏龍茶(瓶裝)', N'10000', N'35', N'飲料')
INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P012', N'錫蘭奶茶(瓶裝)', N'5000', N'20', N'飲料')
INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P013', N'紅茶(瓶裝)', N'1230', N'25', N'飲料')
INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P014', N'台酒花雕雞泡麵(碗裝)', N'10000', N'53', N'食品')
INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P015', N'台酒花雕雞泡麵(碗裝)', N'10000', N'53', N'食品')
INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P016', N'Ipad Pro ', N'1000', N'53420', N'3C')
INSERT INTO [dbo].[ProductTable] ([Model], [Name], [Quantity], [Price], [Category]) VALUES (N'P017', N'筆記型電腦', N'1235', N'33023', N'3C')
